trigger:
  paths:
    include:
      - Weather-app-source-files/**
      - Dockerfiles/Dockerfile

pool:
  name: NishantAgent
  demands:
    - agent.name -equals nishanagent1

variables:
  imageName: 'myapp'  # Change to your app name
  acrName: 'myacr.azurecr.io'  # Replace with your ACR login server

steps:
#  Step 1: Checkout Code
  - task: Checkout@1
    displayName: 'Pull source code from GitHub'

#  Step 2: Install Docker (if needed)
  - task: DockerInstaller@0
    displayName: 'Install Docker'

#  Step 3: Build Docker Image
  - script: |
        docker build -t $(acrName)/$(imageName):$(Build.BuildId) .
    displayName: 'Build Docker Image'

#  Step 4: Login to Azure Container Registry
  - script: |
      echo $(ACR_PASSWORD) | docker login $(acrName) -u $(ACR_USERNAME) --password-stdin
    displayName: 'Authenticate with ACR'

#  Step 5: Push Docker Image with Build Tag
  - script: |
      docker push $(acrName)/$(imageName):$(Build.BuildId)
    displayName: 'Push Image with Build Tag'

#  Step 6: Tag and Push as Latest
  - script: |
      docker tag $(acrName)/$(imageName):$(Build.BuildId) $(acrName)/$(imageName):latest
      docker push $(acrName)/$(imageName):latest
    displayName: 'Tag and Push Latest'