apiVersion: v1
kind: Secret
metadata:
  name: acr-secret
  namespace: default
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJuaXNoYW50LmF6dXJlY3IuaW8iOnsidXNlcm5hbWUiOiJuaXNoYW50IiwicGFzc3dvcmQiOiJMSGE0K2xHN2tOS2ZSQmtaQnMxLzYxdUZ6ZmllY20xVVlTK1lVU00vZWIrQUNSQ1ZPK29zIn19fQ==
  


  #echo -n '{"auths":{"nishant.azurecr.io":{"username":"nishant","password":"<your-password>","email":"nishant@example.com"}}}' | base64